


#include"USART_Private.h"
#include"USART_Config.h"

#define USART_Nu1 			    0
#define USART_Nu2				1
#define USART_Nu6				2




/*Configuration*/

	/*USART_CR1_8BIT_DATA	
	USART_CR1_9BIT_DATA
	
	USART_CR1_RE
	USART_CR1_R_DISABLE
	
    USART_CR1_TE
	USART_CR1_T_DISABLE
	
	
	USART_CR1_EVEN_PARITY	
	USART_CR1_ODD_PARITY

	USART_CR1_PARITY_ENABLE	
	USART_CR1_PARITY_DISABLE
	
	
	USART_CR1_UART_ENABLE
	USART_CR1_UART_DISABLE
	
	
	USART_CR2_ONE_BIT_STOP
	USART_CR2_TWO_BIT_STOP
	
	
	USART_CR1_OVER_SAMPLEBY8	
	USART_CR1_OVER_SAMPLEBY16	*/
	
const UASRT_Cfg_t  UASRT_CfgAr[NUMBER_OF_USART]
{
	[USART_Nu1].USART_EN=USART_CR1_UART_ENABLE
	[USART_Nu1].USART_DataLen=USART_CR1_8BIT_DATA;
	[USART_Nu1].USART_BaudeRate=;
	[USART_Nu1].USART_Parity_EN=USART_CR1_PARITY_ENABLE;
	[USART_Nu1].USART_ParityOption=USART_CR1_EVEN_PARITY;
	[USART_Nu1].USART_StopBitOption=USART_CR2_TWO_BIT_STOP;
	[USART_Nu1].TX_EN=USART_CR1_TE;
	[USART_Nu1].RX_EN=USART_CR1_RE;
	[USART_Nu1].OverSampleOption=USART_CR1_OVER_SAMPLEBY16;
	
	[USART_Nu2].USART_EN=USART_CR1_UART_ENABLE
	[USART_Nu2].USART_DataLen=USART_CR1_8BIT_DATA;
	[USART_Nu2].USART_BaudeRate=;
	[USART_Nu2].USART_Parity_EN=USART_CR1_PARITY_ENABLE;
    [USART_Nu2].USART_ParityOption=USART_CR1_EVEN_PARITY;
    [USART_Nu2].USART_StopBitOption=USART_CR2_TWO_BIT_STOP;
    [USART_Nu2].TX_EN=USART_CR1_TE;
    [USART_Nu2].RX_EN=USART_CR1_RE;
    [USART_Nu2].OverSampleOption=USART_CR1_OVER_SAMPLEBY16;
	
	
	[USART_Nu6].USART_EN=USART_CR1_UART_ENABLE
    [USART_Nu6].USART_DataLen=USART_CR1_8BIT_DATA;
    [USART_Nu6].USART_BaudeRate=;
    [USART_Nu6].USART_Parity_EN=USART_CR1_PARITY_ENABLE;
    [USART_Nu6].USART_ParityOption=USART_CR1_EVEN_PARITY;
    [USART_Nu6].USART_StopBitOption=USART_CR2_TWO_BIT_STOP;
    [USART_Nu6].TX_EN=USART_CR1_TE;
    [USART_Nu6].RX_EN=USART_CR1_RE;
    [USART_Nu6].OverSampleOption=USART_CR1_OVER_SAMPLEBY16;
	
};